import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat, Prompt, Mochiy_Pop_P_One } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const geistMontserrat = Montserrat({
  variable: "--font-geist-montserrat",
  subsets: ["latin"],
});

const geistPrompt = Prompt({
  variable: "--font-geist-prompt",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

const mochiyPop = Mochiy_Pop_P_One({
  variable: "--font-mochiy-pop",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "EyeGuard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${geistMontserrat.variable} ${geistPrompt.variable} ${mochiyPop.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
